version: '3.8'

services:
  mysql:
    image: mysql:8.0  # ✅ on revient à une version stable
    container_name: mysql-bdd-projet
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d


volumes:
  mysql_data:
